/* eslint-disable */
//@ts-nocheck
/**
 * @fileoverview
 * @enhanceable
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

var jspb = require('google-protobuf');
var goog = jspb;
var global = Function('return this')();

var google_protobuf_empty_pb = require('google-protobuf/google/protobuf/empty_pb.js');
goog.exportSymbol('proto.n0stack.internal.n0core.provisioning.blockstorage.CreateEmptyBlockStorageRequest', null, global);
goog.exportSymbol('proto.n0stack.internal.n0core.provisioning.blockstorage.CreateEmptyBlockStorageResponse', null, global);
goog.exportSymbol('proto.n0stack.internal.n0core.provisioning.blockstorage.DeleteBlockStorageRequest', null, global);
goog.exportSymbol('proto.n0stack.internal.n0core.provisioning.blockstorage.FetchBlockStorageRequest', null, global);
goog.exportSymbol('proto.n0stack.internal.n0core.provisioning.blockstorage.FetchBlockStorageResponse', null, global);
goog.exportSymbol('proto.n0stack.internal.n0core.provisioning.blockstorage.ResizeBlockStorageRequest', null, global);

/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.n0stack.internal.n0core.provisioning.blockstorage.CreateEmptyBlockStorageRequest = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.n0stack.internal.n0core.provisioning.blockstorage.CreateEmptyBlockStorageRequest, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.n0stack.internal.n0core.provisioning.blockstorage.CreateEmptyBlockStorageRequest.displayName = 'proto.n0stack.internal.n0core.provisioning.blockstorage.CreateEmptyBlockStorageRequest';
}


if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.n0stack.internal.n0core.provisioning.blockstorage.CreateEmptyBlockStorageRequest.prototype.toObject = function(opt_includeInstance) {
  return proto.n0stack.internal.n0core.provisioning.blockstorage.CreateEmptyBlockStorageRequest.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.n0stack.internal.n0core.provisioning.blockstorage.CreateEmptyBlockStorageRequest} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.n0stack.internal.n0core.provisioning.blockstorage.CreateEmptyBlockStorageRequest.toObject = function(includeInstance, msg) {
  var f, obj = {
    name: jspb.Message.getFieldWithDefault(msg, 1, ""),
    bytes: jspb.Message.getFieldWithDefault(msg, 2, 0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.n0stack.internal.n0core.provisioning.blockstorage.CreateEmptyBlockStorageRequest}
 */
proto.n0stack.internal.n0core.provisioning.blockstorage.CreateEmptyBlockStorageRequest.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.n0stack.internal.n0core.provisioning.blockstorage.CreateEmptyBlockStorageRequest;
  return proto.n0stack.internal.n0core.provisioning.blockstorage.CreateEmptyBlockStorageRequest.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.n0stack.internal.n0core.provisioning.blockstorage.CreateEmptyBlockStorageRequest} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.n0stack.internal.n0core.provisioning.blockstorage.CreateEmptyBlockStorageRequest}
 */
proto.n0stack.internal.n0core.provisioning.blockstorage.CreateEmptyBlockStorageRequest.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setName(value);
      break;
    case 2:
      var value = /** @type {number} */ (reader.readUint64());
      msg.setBytes(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.n0stack.internal.n0core.provisioning.blockstorage.CreateEmptyBlockStorageRequest.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.n0stack.internal.n0core.provisioning.blockstorage.CreateEmptyBlockStorageRequest.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.n0stack.internal.n0core.provisioning.blockstorage.CreateEmptyBlockStorageRequest} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.n0stack.internal.n0core.provisioning.blockstorage.CreateEmptyBlockStorageRequest.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getName();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getBytes();
  if (f !== 0) {
    writer.writeUint64(
      2,
      f
    );
  }
};


/**
 * optional string name = 1;
 * @return {string}
 */
proto.n0stack.internal.n0core.provisioning.blockstorage.CreateEmptyBlockStorageRequest.prototype.getName = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/** @param {string} value */
proto.n0stack.internal.n0core.provisioning.blockstorage.CreateEmptyBlockStorageRequest.prototype.setName = function(value) {
  jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional uint64 bytes = 2;
 * @return {number}
 */
proto.n0stack.internal.n0core.provisioning.blockstorage.CreateEmptyBlockStorageRequest.prototype.getBytes = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 2, 0));
};


/** @param {number} value */
proto.n0stack.internal.n0core.provisioning.blockstorage.CreateEmptyBlockStorageRequest.prototype.setBytes = function(value) {
  jspb.Message.setProto3IntField(this, 2, value);
};



/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.n0stack.internal.n0core.provisioning.blockstorage.CreateEmptyBlockStorageResponse = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.n0stack.internal.n0core.provisioning.blockstorage.CreateEmptyBlockStorageResponse, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.n0stack.internal.n0core.provisioning.blockstorage.CreateEmptyBlockStorageResponse.displayName = 'proto.n0stack.internal.n0core.provisioning.blockstorage.CreateEmptyBlockStorageResponse';
}


if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.n0stack.internal.n0core.provisioning.blockstorage.CreateEmptyBlockStorageResponse.prototype.toObject = function(opt_includeInstance) {
  return proto.n0stack.internal.n0core.provisioning.blockstorage.CreateEmptyBlockStorageResponse.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.n0stack.internal.n0core.provisioning.blockstorage.CreateEmptyBlockStorageResponse} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.n0stack.internal.n0core.provisioning.blockstorage.CreateEmptyBlockStorageResponse.toObject = function(includeInstance, msg) {
  var f, obj = {
    path: jspb.Message.getFieldWithDefault(msg, 3, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.n0stack.internal.n0core.provisioning.blockstorage.CreateEmptyBlockStorageResponse}
 */
proto.n0stack.internal.n0core.provisioning.blockstorage.CreateEmptyBlockStorageResponse.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.n0stack.internal.n0core.provisioning.blockstorage.CreateEmptyBlockStorageResponse;
  return proto.n0stack.internal.n0core.provisioning.blockstorage.CreateEmptyBlockStorageResponse.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.n0stack.internal.n0core.provisioning.blockstorage.CreateEmptyBlockStorageResponse} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.n0stack.internal.n0core.provisioning.blockstorage.CreateEmptyBlockStorageResponse}
 */
proto.n0stack.internal.n0core.provisioning.blockstorage.CreateEmptyBlockStorageResponse.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.setPath(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.n0stack.internal.n0core.provisioning.blockstorage.CreateEmptyBlockStorageResponse.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.n0stack.internal.n0core.provisioning.blockstorage.CreateEmptyBlockStorageResponse.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.n0stack.internal.n0core.provisioning.blockstorage.CreateEmptyBlockStorageResponse} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.n0stack.internal.n0core.provisioning.blockstorage.CreateEmptyBlockStorageResponse.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getPath();
  if (f.length > 0) {
    writer.writeString(
      3,
      f
    );
  }
};


/**
 * optional string path = 3;
 * @return {string}
 */
proto.n0stack.internal.n0core.provisioning.blockstorage.CreateEmptyBlockStorageResponse.prototype.getPath = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/** @param {string} value */
proto.n0stack.internal.n0core.provisioning.blockstorage.CreateEmptyBlockStorageResponse.prototype.setPath = function(value) {
  jspb.Message.setProto3StringField(this, 3, value);
};



/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.n0stack.internal.n0core.provisioning.blockstorage.FetchBlockStorageRequest = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.n0stack.internal.n0core.provisioning.blockstorage.FetchBlockStorageRequest, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.n0stack.internal.n0core.provisioning.blockstorage.FetchBlockStorageRequest.displayName = 'proto.n0stack.internal.n0core.provisioning.blockstorage.FetchBlockStorageRequest';
}


if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.n0stack.internal.n0core.provisioning.blockstorage.FetchBlockStorageRequest.prototype.toObject = function(opt_includeInstance) {
  return proto.n0stack.internal.n0core.provisioning.blockstorage.FetchBlockStorageRequest.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.n0stack.internal.n0core.provisioning.blockstorage.FetchBlockStorageRequest} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.n0stack.internal.n0core.provisioning.blockstorage.FetchBlockStorageRequest.toObject = function(includeInstance, msg) {
  var f, obj = {
    name: jspb.Message.getFieldWithDefault(msg, 1, ""),
    bytes: jspb.Message.getFieldWithDefault(msg, 2, 0),
    sourceUrl: jspb.Message.getFieldWithDefault(msg, 3, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.n0stack.internal.n0core.provisioning.blockstorage.FetchBlockStorageRequest}
 */
proto.n0stack.internal.n0core.provisioning.blockstorage.FetchBlockStorageRequest.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.n0stack.internal.n0core.provisioning.blockstorage.FetchBlockStorageRequest;
  return proto.n0stack.internal.n0core.provisioning.blockstorage.FetchBlockStorageRequest.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.n0stack.internal.n0core.provisioning.blockstorage.FetchBlockStorageRequest} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.n0stack.internal.n0core.provisioning.blockstorage.FetchBlockStorageRequest}
 */
proto.n0stack.internal.n0core.provisioning.blockstorage.FetchBlockStorageRequest.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setName(value);
      break;
    case 2:
      var value = /** @type {number} */ (reader.readUint64());
      msg.setBytes(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.setSourceUrl(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.n0stack.internal.n0core.provisioning.blockstorage.FetchBlockStorageRequest.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.n0stack.internal.n0core.provisioning.blockstorage.FetchBlockStorageRequest.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.n0stack.internal.n0core.provisioning.blockstorage.FetchBlockStorageRequest} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.n0stack.internal.n0core.provisioning.blockstorage.FetchBlockStorageRequest.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getName();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getBytes();
  if (f !== 0) {
    writer.writeUint64(
      2,
      f
    );
  }
  f = message.getSourceUrl();
  if (f.length > 0) {
    writer.writeString(
      3,
      f
    );
  }
};


/**
 * optional string name = 1;
 * @return {string}
 */
proto.n0stack.internal.n0core.provisioning.blockstorage.FetchBlockStorageRequest.prototype.getName = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/** @param {string} value */
proto.n0stack.internal.n0core.provisioning.blockstorage.FetchBlockStorageRequest.prototype.setName = function(value) {
  jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional uint64 bytes = 2;
 * @return {number}
 */
proto.n0stack.internal.n0core.provisioning.blockstorage.FetchBlockStorageRequest.prototype.getBytes = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 2, 0));
};


/** @param {number} value */
proto.n0stack.internal.n0core.provisioning.blockstorage.FetchBlockStorageRequest.prototype.setBytes = function(value) {
  jspb.Message.setProto3IntField(this, 2, value);
};


/**
 * optional string source_url = 3;
 * @return {string}
 */
proto.n0stack.internal.n0core.provisioning.blockstorage.FetchBlockStorageRequest.prototype.getSourceUrl = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/** @param {string} value */
proto.n0stack.internal.n0core.provisioning.blockstorage.FetchBlockStorageRequest.prototype.setSourceUrl = function(value) {
  jspb.Message.setProto3StringField(this, 3, value);
};



/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.n0stack.internal.n0core.provisioning.blockstorage.FetchBlockStorageResponse = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.n0stack.internal.n0core.provisioning.blockstorage.FetchBlockStorageResponse, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.n0stack.internal.n0core.provisioning.blockstorage.FetchBlockStorageResponse.displayName = 'proto.n0stack.internal.n0core.provisioning.blockstorage.FetchBlockStorageResponse';
}


if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.n0stack.internal.n0core.provisioning.blockstorage.FetchBlockStorageResponse.prototype.toObject = function(opt_includeInstance) {
  return proto.n0stack.internal.n0core.provisioning.blockstorage.FetchBlockStorageResponse.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.n0stack.internal.n0core.provisioning.blockstorage.FetchBlockStorageResponse} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.n0stack.internal.n0core.provisioning.blockstorage.FetchBlockStorageResponse.toObject = function(includeInstance, msg) {
  var f, obj = {
    path: jspb.Message.getFieldWithDefault(msg, 3, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.n0stack.internal.n0core.provisioning.blockstorage.FetchBlockStorageResponse}
 */
proto.n0stack.internal.n0core.provisioning.blockstorage.FetchBlockStorageResponse.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.n0stack.internal.n0core.provisioning.blockstorage.FetchBlockStorageResponse;
  return proto.n0stack.internal.n0core.provisioning.blockstorage.FetchBlockStorageResponse.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.n0stack.internal.n0core.provisioning.blockstorage.FetchBlockStorageResponse} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.n0stack.internal.n0core.provisioning.blockstorage.FetchBlockStorageResponse}
 */
proto.n0stack.internal.n0core.provisioning.blockstorage.FetchBlockStorageResponse.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.setPath(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.n0stack.internal.n0core.provisioning.blockstorage.FetchBlockStorageResponse.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.n0stack.internal.n0core.provisioning.blockstorage.FetchBlockStorageResponse.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.n0stack.internal.n0core.provisioning.blockstorage.FetchBlockStorageResponse} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.n0stack.internal.n0core.provisioning.blockstorage.FetchBlockStorageResponse.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getPath();
  if (f.length > 0) {
    writer.writeString(
      3,
      f
    );
  }
};


/**
 * optional string path = 3;
 * @return {string}
 */
proto.n0stack.internal.n0core.provisioning.blockstorage.FetchBlockStorageResponse.prototype.getPath = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/** @param {string} value */
proto.n0stack.internal.n0core.provisioning.blockstorage.FetchBlockStorageResponse.prototype.setPath = function(value) {
  jspb.Message.setProto3StringField(this, 3, value);
};



/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.n0stack.internal.n0core.provisioning.blockstorage.DeleteBlockStorageRequest = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.n0stack.internal.n0core.provisioning.blockstorage.DeleteBlockStorageRequest, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.n0stack.internal.n0core.provisioning.blockstorage.DeleteBlockStorageRequest.displayName = 'proto.n0stack.internal.n0core.provisioning.blockstorage.DeleteBlockStorageRequest';
}


if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.n0stack.internal.n0core.provisioning.blockstorage.DeleteBlockStorageRequest.prototype.toObject = function(opt_includeInstance) {
  return proto.n0stack.internal.n0core.provisioning.blockstorage.DeleteBlockStorageRequest.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.n0stack.internal.n0core.provisioning.blockstorage.DeleteBlockStorageRequest} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.n0stack.internal.n0core.provisioning.blockstorage.DeleteBlockStorageRequest.toObject = function(includeInstance, msg) {
  var f, obj = {
    path: jspb.Message.getFieldWithDefault(msg, 3, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.n0stack.internal.n0core.provisioning.blockstorage.DeleteBlockStorageRequest}
 */
proto.n0stack.internal.n0core.provisioning.blockstorage.DeleteBlockStorageRequest.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.n0stack.internal.n0core.provisioning.blockstorage.DeleteBlockStorageRequest;
  return proto.n0stack.internal.n0core.provisioning.blockstorage.DeleteBlockStorageRequest.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.n0stack.internal.n0core.provisioning.blockstorage.DeleteBlockStorageRequest} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.n0stack.internal.n0core.provisioning.blockstorage.DeleteBlockStorageRequest}
 */
proto.n0stack.internal.n0core.provisioning.blockstorage.DeleteBlockStorageRequest.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.setPath(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.n0stack.internal.n0core.provisioning.blockstorage.DeleteBlockStorageRequest.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.n0stack.internal.n0core.provisioning.blockstorage.DeleteBlockStorageRequest.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.n0stack.internal.n0core.provisioning.blockstorage.DeleteBlockStorageRequest} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.n0stack.internal.n0core.provisioning.blockstorage.DeleteBlockStorageRequest.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getPath();
  if (f.length > 0) {
    writer.writeString(
      3,
      f
    );
  }
};


/**
 * optional string path = 3;
 * @return {string}
 */
proto.n0stack.internal.n0core.provisioning.blockstorage.DeleteBlockStorageRequest.prototype.getPath = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/** @param {string} value */
proto.n0stack.internal.n0core.provisioning.blockstorage.DeleteBlockStorageRequest.prototype.setPath = function(value) {
  jspb.Message.setProto3StringField(this, 3, value);
};



/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.n0stack.internal.n0core.provisioning.blockstorage.ResizeBlockStorageRequest = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.n0stack.internal.n0core.provisioning.blockstorage.ResizeBlockStorageRequest, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.n0stack.internal.n0core.provisioning.blockstorage.ResizeBlockStorageRequest.displayName = 'proto.n0stack.internal.n0core.provisioning.blockstorage.ResizeBlockStorageRequest';
}


if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.n0stack.internal.n0core.provisioning.blockstorage.ResizeBlockStorageRequest.prototype.toObject = function(opt_includeInstance) {
  return proto.n0stack.internal.n0core.provisioning.blockstorage.ResizeBlockStorageRequest.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.n0stack.internal.n0core.provisioning.blockstorage.ResizeBlockStorageRequest} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.n0stack.internal.n0core.provisioning.blockstorage.ResizeBlockStorageRequest.toObject = function(includeInstance, msg) {
  var f, obj = {
    bytes: jspb.Message.getFieldWithDefault(msg, 2, 0),
    path: jspb.Message.getFieldWithDefault(msg, 3, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.n0stack.internal.n0core.provisioning.blockstorage.ResizeBlockStorageRequest}
 */
proto.n0stack.internal.n0core.provisioning.blockstorage.ResizeBlockStorageRequest.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.n0stack.internal.n0core.provisioning.blockstorage.ResizeBlockStorageRequest;
  return proto.n0stack.internal.n0core.provisioning.blockstorage.ResizeBlockStorageRequest.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.n0stack.internal.n0core.provisioning.blockstorage.ResizeBlockStorageRequest} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.n0stack.internal.n0core.provisioning.blockstorage.ResizeBlockStorageRequest}
 */
proto.n0stack.internal.n0core.provisioning.blockstorage.ResizeBlockStorageRequest.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 2:
      var value = /** @type {number} */ (reader.readUint64());
      msg.setBytes(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.setPath(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.n0stack.internal.n0core.provisioning.blockstorage.ResizeBlockStorageRequest.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.n0stack.internal.n0core.provisioning.blockstorage.ResizeBlockStorageRequest.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.n0stack.internal.n0core.provisioning.blockstorage.ResizeBlockStorageRequest} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.n0stack.internal.n0core.provisioning.blockstorage.ResizeBlockStorageRequest.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getBytes();
  if (f !== 0) {
    writer.writeUint64(
      2,
      f
    );
  }
  f = message.getPath();
  if (f.length > 0) {
    writer.writeString(
      3,
      f
    );
  }
};


/**
 * optional uint64 bytes = 2;
 * @return {number}
 */
proto.n0stack.internal.n0core.provisioning.blockstorage.ResizeBlockStorageRequest.prototype.getBytes = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 2, 0));
};


/** @param {number} value */
proto.n0stack.internal.n0core.provisioning.blockstorage.ResizeBlockStorageRequest.prototype.setBytes = function(value) {
  jspb.Message.setProto3IntField(this, 2, value);
};


/**
 * optional string path = 3;
 * @return {string}
 */
proto.n0stack.internal.n0core.provisioning.blockstorage.ResizeBlockStorageRequest.prototype.getPath = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/** @param {string} value */
proto.n0stack.internal.n0core.provisioning.blockstorage.ResizeBlockStorageRequest.prototype.setPath = function(value) {
  jspb.Message.setProto3StringField(this, 3, value);
};


goog.object.extend(exports, proto.n0stack.internal.n0core.provisioning.blockstorage);
